---
#
# Install/run rust dedicated server
#

- name: Enable multiverse repository
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security multiverse"

- name: Add i386 Architecture
  command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch
  when: ansible_architecture != 'i386'
  register: archrc

- name: Update APT Cache for i386
  apt:
    update_cache: true
  when: archrc is defined and archrc.changed

- name: accept steam license
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Install steamcmd
  apt: name=steamcmd state=latest

############

- name: Setup rustds user
  user:
    name=rustds shell=/sbin/nologin

- name: Setup rustds server path
  file:
    path=/home/rustds/server
    state=directory
    owner=rustds
    recurse=yes
    mode=0755

- name: Download game data
  shell: "/usr/games/steamcmd +force_install_dir /home/rustds/server +login {{steam_user}} +app_update 258550 validate +quit"
  args:
    chdir: /home/rustds
    executable: /bin/bash
  become_user: rustds
  ignore_errors: true

- name: Install rustds systemd unit file
  copy:
    src=rustds.service
    dest=/etc/systemd/system/rustds.service
    owner=root
    group=root
    mode=0644
    force=no
  ignore_errors: true

- name: Copy startup Script
  copy:
    src=startserver.sh
    dest=/home/rustds/server/startserver.sh
    owner=rustds
    group=rustds
    mode=0755
    force=no
  ignore_errors: true

- name: Copy server.cfg
  copy:
    src=server.cfg
    dest=/home/rustds/server/server/my_server_identity/cfg/server.cfg
    owner=rustds
    group=rustds
    mode=0644
    force=no
  ignore_errors: true

- name: Copy users.cfg
  copy:
    src=users.cfg
    dest=/home/rustds/server/server/my_server_identity/cfg/users.cfg
    owner=rustds
    group=rustds
    mode=0644
    force=no
  ignore_errors: true

- name: Restart rustds service
  command: systemctl restart rustds.service
  ignore_errors: true

- name: Enable rustds service
  service: name=rustds state=started enabled=true
  ignore_errors: true
